# Generated by Django 5.2.1 on 2025-06-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='banner_image',
            field=models.ImageField(default='artist_banners/default_banner.jpg', upload_to='artist_banners/'),
            preserve_default=False,
        ),
    ]
